// This function only works for single row insertions where the row's id is generated by postgres
const createInsertQuery = (table, colsObj) => {
    const colsArr = Object.keys(colsObj);
    const valsArr = Object.values(colsObj);

    let columnCount = 0;
    let colsStr = "";
    let valsStr = "";

    for (const col of colsArr) {
        columnCount += 1;
        colsStr += `${col}${(columnCount === colsArr.length) ? "" : `,
            `}`
        valsStr += `$${columnCount.toString()}${(columnCount === colsArr.length) ? "" : `, `}`
    }

    const insertQuery = `
        INSERT INTO ${table} (${colsStr})
        VALUES (${valsStr})
        RETURNING id`;

    return { insertQuery, valsArr };
};

module.exports = createInsertQuery;